stages:
    - badges

badges:
  stage: badges
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"'
  tags:
    - docker
  script:
    - echo "collecting stats for badges"
    - line_count=`find . -name '*.sh' | sed 's/.*/\"&\"/' | xargs cat | wc -l`
    - echo "{\"line_count\":\"$line_count\"}" > badges.json
  after_script:
    - echo "finished collecting stats"
  artifacts:
    paths:
        - badges.json
    when: always
    expire_in: 1 day