#!/usr/bin/env bash
#
# Setup a python+jupyter development environment

# fail-fast
set -o errexit
set -o nounset
set -o pipefail

# variables needed
readonly SCRIPT_PATH="$(dirname "${BASH_SOURCE[0]}")"
readonly SCRIPT_NAME="${PWD##*/}"
readonly ERROR_PARSING_OPTIONS=80
readonly ERROR_CODE=81
verbose="false"
skip_docker_check_flag="false"
build_flag="false"
default_flag="false"
create_flag="false"
run_flag="false"
stop_flag="false"

source "${SCRIPT_PATH}/utils.sh"
source "${SCRIPT_PATH}/image.sh"
source "${SCRIPT_PATH}/container.sh"
source "${SCRIPT_PATH}/run.sh"


die() {
    local -r msg="${1}"
    local -r code="${2:-90}"
    echo "${msg}" >&2
    exit "${code}"
}

# to send message in case of verbose output
msg() {
    local -r msg="${1}"
    if [[ $verbose == 'true' ]]; then echo "${msg}"; fi
}


usage () {
    cat <<USAGE_TEXT
Usage: env/setup [-h | --help] [-v | --verbose] [-b | --build] [-d | --default]
                 [-c | --create] [-r | --run] [--skip-check] [--lc] [--li]
                 [--show-defaults] [--version] [--check-updates] [--update]
DESCRIPTION
    Setup a python+jupyter development environment using containers trough Docker
OPTIONS:
    -h, --help
        Print this help and exit.
    -v, --verbose
        Verbose output
    -b, --build
        Build a new image skipping the lookup for new images
    -d, --default
        Build a new image using default stack versions
        Creates container using name of the parent directory and a random port
        Use --show-defaults to list the defaults values
    -c, --create
        Create a container from a existing image
    -r, --run
        Run a existing container
    --stop
        Stop a running container
    --skip-check
        Skip checking if docker is installed and initialized
    --li
        List available images with python and jupyterlab
    --lc
        List available containers with python and jupyterlab
    --list-config
        List configuration values (stack version used, python and jupyter lab)
    --version
        Display version information
    --check-updates
        Checks for package updates
AUTHOR
    Marco Ramos
USAGE_TEXT
}



parse_user_options() {
    local -r args=("${@}")
    local opts
    # The following code works perfectly for 
    opts=$(getopt --options h,v,b,d,c,r \
    --long help,verbose,build,default,create,run,stop,skip-check,lc,li,list-config,version,check-update \
    -- "${args[@]}" 2> /dev/null) || {
        usage
        die "error: parsing options" "${ERROR_PARSING_OPTIONS}"
    }
    eval set -- "${opts}"
    while true; do
        case "${1}" in
            -h|--help)
                usage
                exit 0
                shift
                ;;
            -v|--verbose)
                verbose="true"
                shift
                ;;
            -b|--build)
                build_flag="true"
                shift
                ;;
            -d|--default)
                default_flag="true"
                shift
                ;;
            -c|--create)
                create_flag="true"
                shift
                ;;
            -r|--run)
                run_flag="true"
                shift
                ;;
            --stop)
                stop_flag="true"
                shift
                ;;
            --skip-check)
                skip_docker_check_flag="true"
                shift
                ;;
            --lc)
                msg "Looking for python+jupyter environments in containers"
                list_containers
                exit 0
                ;;
            --li)
                msg "Looking for python+jupyter images"
                get_images
                exit 0
                ;;
            --list-config)
                list_configuration
                exit 0
                ;;
            --version)
                echo "py-jupyter-env version: "$(read_config "VERSION")
                exit 0
                ;;
            --check-update)
                check_updates
                exit 0
                ;;
            --)
                break
                ;;
            *)
                usage
                exit 0
                ;;
        esac
    done
}
parse_user_options "${@}"

if [[ $build_flag == "false" && $create_flag == "false" && $run_flag == "false" \
    && $stop_flag == "false" ]]; then
    usage
    exit 0
fi

if [[ $skip_docker_check_flag == "false" ]]; then
    # Check if docker is installed
    __temp=$(which docker)  
    if [[ $? -eq 1 ]]; then
        die "Docker instalation not found, please install docker first!"
    fi

    # Check if docker is initilized
    docker_version=$(docker --version)
    if [[ $? -eq 1 ]];
    then
        die "Docker is installed but not started, please start docker daemon!"
    else
        msg "Found Docker: ${docker_version}"
    fi
fi

set_defaults

if [[ $build_flag == "true" ]]; then
    if [[ $default_flag == "false" ]]; then prompt_versions; fi
    build_image
fi

if [[ $create_flag == "true" ]]; then
    if [[ $build_flag == "false" ]]; then prompt_images; fi
    prompt_container
    create_container
fi

if [[ $run_flag == "true" ]]; then
    run_container
fi

if [[ $stop_flag == "true" ]]; then
    stop_container
fi

msg "Exiting Script..."
exit 0
